apiVersion: apps/v1
kind: Deployment
metadata:
    name: express-deployment
    labels:
        app: express
spec:
    replicas: 2
    selector:
        matchLabels:
            app: express
    template:
        metadata:
            labels:
                app: express
        spec:
            containers:
                - name: express
                  image: europe-north1-docker.pkg.dev/sisu-tech/docker-registry/express:latest
                  ports:
                      - containerPort: 3000
