apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express
spec:
  replicas: 2
  selector:
    matchLabels:
    app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: europe-north1-docker.pkg.dev/sisu-tech/docker-registry/express:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

  service:
    metadata:
    name: express
  spec:
    selector:
      app: express
    ports:
    - protocol: TCP
        port : 80
       argetPort : 3000
      type : LoadBalancer