---
name: docker
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sisu-tech
      PROJECT_ID: infrastructure-task
    steps:
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker Image to GCR
      env:
        GIT_TAG: v0.1.0
      run: |- 
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    - name: Checkout repository
      uses: actions/checkout@v3

